export interface Monster {
  name: string
  cr: number
}

export const MONSTERS: Monster[] = [
  { name: "Aboleth", cr: 10 },
  { name: "Acolyte", cr: 0.25 },
  { name: "Adult Black Dragon", cr: 14 },
  { name: "Adult Blue Dragon", cr: 16 },
  { name: "Adult Brass Dragon", cr: 13 },
  { name: "Adult Bronze Dragon", cr: 15 },
  { name: "Adult Copper Dragon", cr: 14 },
  { name: "Adult Gold Dragon", cr: 17 },
  { name: "Adult Green Dragon", cr: 15 },
  { name: "Adult Red Dragon", cr: 17 },
  { name: "Adult Silver Dragon", cr: 16 },
  { name: "Adult White Dragon", cr: 13 },
  { name: "Air Elemental", cr: 5 },
  { name: "Ancient Black Dragon", cr: 21 },
  { name: "Ancient Blue Dragon", cr: 23 },
  { name: "Ancient Brass Dragon", cr: 20 },
  { name: "Ancient Bronze Dragon", cr: 22 },
  { name: "Ancient Copper Dragon", cr: 21 },
  { name: "Ancient Gold Dragon", cr: 24 },
  { name: "Ancient Green Dragon", cr: 22 },
  { name: "Ancient Red Dragon", cr: 24 },
  { name: "Ancient Silver Dragon", cr: 23 },
  { name: "Ancient White Dragon", cr: 20 },
  { name: "Androsphinx", cr: 17 },
  { name: "Animated Armor", cr: 1 },
  { name: "Ankheg", cr: 2 },
  { name: "Ape", cr: 0.5 },
  { name: "Archmage", cr: 12 },
  { name: "Assassin", cr: 8 },
  { name: "Awakened Shrub", cr: 0 },
  { name: "Awakened Tree", cr: 2 },
  { name: "Axe Beak", cr: 0.25 },
  { name: "Azer", cr: 2 },
  { name: "Baboon", cr: 0 },
  { name: "Badger", cr: 0 },
  { name: "Balor", cr: 19 },
  { name: "Bandit", cr: 0.125 },
  { name: "Bandit Captain", cr: 2 },
  { name: "Banshee", cr: 4 },
  { name: "Barbed Devil", cr: 5 },
  { name: "Basilisk", cr: 3 },
  { name: "Bat", cr: 0 },
  { name: "Bearded Devil", cr: 3 },
  { name: "Behir", cr: 11 },
  { name: "Berserker", cr: 2 },
  { name: "Black Bear", cr: 0.5 },
  { name: "Black Dragon Wyrmling", cr: 2 },
  { name: "Black Pudding", cr: 4 },
  { name: "Blink Dog", cr: 0.25 },
  { name: "Blood Hawk", cr: 0.125 },
  { name: "Blue Dragon Wyrmling", cr: 3 },
  { name: "Boar", cr: 0.25 },
  { name: "Bone Devil", cr: 9 },
  { name: "Brass Dragon Wyrmling", cr: 1 },
  { name: "Bronze Dragon Wyrmling", cr: 2 },
  { name: "Brown Bear", cr: 1 },
  { name: "Bugbear", cr: 1 },
  { name: "Bulette", cr: 5 },
  { name: "Camel", cr: 0.125 },
  { name: "Cat", cr: 0 },
  { name: "Centaur", cr: 2 },
  { name: "Chain Devil", cr: 8 },
  { name: "Chimera", cr: 6 },
  { name: "Chuul", cr: 4 },
  { name: "Clay Golem", cr: 9 },
  { name: "Cloaker", cr: 8 },
  { name: "Cloud Giant", cr: 9 },
  { name: "Cockatrice", cr: 0.5 },
  { name: "Commoner", cr: 0 },
  { name: "Constrictor Snake", cr: 0.25 },
  { name: "Copper Dragon Wyrmling", cr: 1 },
  { name: "Couatl", cr: 4 },
  { name: "Crab", cr: 0 },
  { name: "Crocodile", cr: 0.5 },
  { name: "Cult Fanatic", cr: 2 },
  { name: "Cultist", cr: 0.125 },
  { name: "Darkmantle", cr: 0.5 },
  { name: "Death Dog", cr: 1 },
  { name: "Deep Gnome", cr: 0.5 },
  { name: "Deer", cr: 0 },
  { name: "Deva", cr: 10 },
  { name: "Dire Wolf", cr: 1 },
  { name: "Djinni", cr: 11 },
  { name: "Doppelganger", cr: 3 },
  { name: "Draft Horse", cr: 0.25 },
  { name: "Dragon Turtle", cr: 17 },
  { name: "Dretch", cr: 0.25 },
  { name: "Drider", cr: 6 },
  { name: "Drow", cr: 0.25 },
  { name: "Druid", cr: 2 },
  { name: "Dryad", cr: 1 },
  { name: "Duergar", cr: 1 },
  { name: "Dust Mephit", cr: 0.5 },
  { name: "Eagle", cr: 0 },
  { name: "Earth Elemental", cr: 5 },
  { name: "Efreeti", cr: 11 },
  { name: "Elephant", cr: 4 },
  { name: "Elk", cr: 0.25 },
  { name: "Erinyes", cr: 12 },
  { name: "Ettercap", cr: 2 },
  { name: "Ettin", cr: 4 },
  { name: "Fire Elemental", cr: 5 },
  { name: "Fire Giant", cr: 9 },
  { name: "Flesh Golem", cr: 5 },
  { name: "Flying Snake", cr: 0.125 },
  { name: "Flying Sword", cr: 0.25 },
  { name: "Frog", cr: 0 },
  { name: "Frost Giant", cr: 8 },
  { name: "Gargoyle", cr: 2 },
  { name: "Gelatinous Cube", cr: 2 },
  { name: "Ghast", cr: 2 },
  { name: "Ghost", cr: 4 },
  { name: "Ghoul", cr: 1 },
  { name: "Giant Ape", cr: 7 },
  { name: "Giant Badger", cr: 0.25 },
  { name: "Giant Bat", cr: 0.25 },
  { name: "Giant Boar", cr: 2 },
  { name: "Giant Centipede", cr: 0.25 },
  { name: "Giant Constrictor Snake", cr: 2 },
  { name: "Giant Crab", cr: 0.125 },
  { name: "Giant Crocodile", cr: 5 },
  { name: "Giant Eagle", cr: 1 },
  { name: "Giant Elk", cr: 2 },
  { name: "Giant Fire Beetle", cr: 0 },
  { name: "Giant Frog", cr: 0.25 },
  { name: "Giant Goat", cr: 0.5 },
  { name: "Giant Hyena", cr: 1 },
  { name: "Giant Lizard", cr: 0.25 },
  { name: "Giant Octopus", cr: 1 },
  { name: "Giant Owl", cr: 0.25 },
  { name: "Giant Poisonous Snake", cr: 0.25 },
  { name: "Giant Rat", cr: 0.125 },
  { name: "Giant Scorpion", cr: 3 },
  { name: "Giant Sea Horse", cr: 0.5 },
  { name: "Giant Shark", cr: 5 },
  { name: "Giant Spider", cr: 1 },
  { name: "Giant Toad", cr: 1 },
  { name: "Giant Vulture", cr: 1 },
  { name: "Giant Wasp", cr: 0.5 },
  { name: "Giant Weasel", cr: 0.125 },
  { name: "Giant Wolf Spider", cr: 0.25 },
  { name: "Gibbering Mouther", cr: 2 },
  { name: "Glabrezu", cr: 9 },
  { name: "Gladiator", cr: 5 },
  { name: "Gnoll", cr: 0.5 },
  { name: "Goat", cr: 0 },
  { name: "Goblin", cr: 0.25 },
  { name: "Gold Dragon Wyrmling", cr: 3 },
  { name: "Gorgon", cr: 5 },
  { name: "Gray Ooze", cr: 0.5 },
  { name: "Green Dragon Wyrmling", cr: 2 },
  { name: "Green Hag", cr: 3 },
  { name: "Grick", cr: 2 },
  { name: "Griffon", cr: 2 },
  { name: "Grimlock", cr: 0.25 },
  { name: "Guard", cr: 0.125 },
  { name: "Guardian Naga", cr: 10 },
  { name: "Gynosphinx", cr: 11 },
  { name: "Half-Red Dragon Veteran", cr: 5 },
  { name: "Harpy", cr: 1 },
  { name: "Hawk", cr: 0 },
  { name: "Hell Hound", cr: 3 },
  { name: "Hezrou", cr: 8 },
  { name: "Hill Giant", cr: 5 },
  { name: "Hippogriff", cr: 1 },
  { name: "Hobgoblin", cr: 0.5 },
  { name: "Homunculus", cr: 0 },
  { name: "Horned Devil", cr: 11 },
  { name: "Hunter Shark", cr: 2 },
  { name: "Hydra", cr: 8 },
  { name: "Hyena", cr: 0 },
  { name: "Ice Devil", cr: 14 },
  { name: "Ice Mephit", cr: 0.5 },
  { name: "Imp", cr: 1 },
  { name: "Invisible Stalker", cr: 6 },
  { name: "Iron Golem", cr: 16 },
  { name: "Jackal", cr: 0 },
  { name: "Killer Whale", cr: 3 },
  { name: "Knight", cr: 3 },
  { name: "Kobold", cr: 0.125 },
  { name: "Kraken", cr: 23 },
  { name: "Lamia", cr: 4 },
  { name: "Lemure", cr: 0 },
  { name: "Lich", cr: 21 },
  { name: "Lion", cr: 1 },
  { name: "Lizard", cr: 0 },
  { name: "Lizardfolk", cr: 0.5 },
  { name: "Mage", cr: 6 },
  { name: "Magma Mephit", cr: 0.5 },
  { name: "Magmin", cr: 0.5 },
  { name: "Mammoth", cr: 6 },
  { name: "Manticore", cr: 3 },
  { name: "Marilith", cr: 16 },
  { name: "Mastiff", cr: 0.125 },
  { name: "Medusa", cr: 6 },
  { name: "Merfolk", cr: 0.125 },
  { name: "Merrow", cr: 2 },
  { name: "Mimic", cr: 2 },
  { name: "Minotaur", cr: 3 },
  { name: "Minotaur Skeleton", cr: 2 },
  { name: "Mule", cr: 0.125 },
  { name: "Mummy", cr: 3 },
  { name: "Mummy Lord", cr: 15 },
  { name: "Nalfeshnee", cr: 13 },
  { name: "Night Hag", cr: 5 },
  { name: "Nightmare", cr: 3 },
  { name: "Noble", cr: 0.125 },
  { name: "Ochre Jelly", cr: 2 },
  { name: "Octopus", cr: 0 },
  { name: "Ogre", cr: 2 },
  { name: "Ogre Zombie", cr: 2 },
  { name: "Oni", cr: 7 },
  { name: "Orc", cr: 0.5 },
  { name: "Otyugh", cr: 5 },
  { name: "Owl", cr: 0 },
  { name: "Owlbear", cr: 3 },
  { name: "Panther", cr: 0.25 },
  { name: "Pegasus", cr: 2 },
  { name: "Phase Spider", cr: 3 },
  { name: "Pit Fiend", cr: 20 },
  { name: "Planetar", cr: 16 },
  { name: "Plesiosaurus", cr: 2 },
  { name: "Poisonous Snake", cr: 0.125 },
  { name: "Polar Bear", cr: 2 },
  { name: "Pony", cr: 0.125 },
  { name: "Priest", cr: 2 },
  { name: "Pseudodragon", cr: 0.25 },
  { name: "Purple Worm", cr: 15 },
  { name: "Quasit", cr: 1 },
  { name: "Quipper", cr: 0 },
  { name: "Rakshasa", cr: 13 },
  { name: "Rat", cr: 0 },
  { name: "Raven", cr: 0 },
  { name: "Red Dragon Wyrmling", cr: 4 },
  { name: "Reef Shark", cr: 0.5 },
  { name: "Remorhaz", cr: 11 },
  { name: "Rhinoceros", cr: 2 },
  { name: "Riding Horse", cr: 0.25 },
  { name: "Roc", cr: 11 },
  { name: "Roper", cr: 5 },
  { name: "Rug of Smothering", cr: 2 },
  { name: "Rust Monster", cr: 0.5 },
  { name: "Saber-Toothed Tiger", cr: 2 },
  { name: "Sahuagin", cr: 0.5 },
  { name: "Salamander", cr: 5 },
  { name: "Satyr", cr: 0.5 },
  { name: "Scorpion", cr: 0 },
  { name: "Scout", cr: 0.5 },
  { name: "Sea Hag", cr: 2 },
  { name: "Sea Horse", cr: 0 },
  { name: "Shadow", cr: 0.5 },
  { name: "Shambling Mound", cr: 5 },
  { name: "Shield Guardian", cr: 7 },
  { name: "Shrieker", cr: 0 },
  { name: "Silver Dragon Wyrmling", cr: 2 },
  { name: "Skeleton", cr: 0.25 },
  { name: "Solar", cr: 21 },
  { name: "Specter", cr: 1 },
  { name: "Spider", cr: 0 },
  { name: "Spirit Naga", cr: 8 },
  { name: "Sprite", cr: 0.25 },
  { name: "Spy", cr: 1 },
  { name: "Steam Mephit", cr: 0.25 },
  { name: "Stirge", cr: 0.125 },
  { name: "Stone Giant", cr: 7 },
  { name: "Stone Golem", cr: 10 },
  { name: "Storm Giant", cr: 13 },
  { name: "Succubus/Incubus", cr: 4 },
  { name: "Swarm of Bats", cr: 0.25 },
  { name: "Swarm of Insects", cr: 0.5 },
  { name: "Swarm of Poisonous Snakes", cr: 2 },
  { name: "Swarm of Quippers", cr: 1 },
  { name: "Swarm of Rats", cr: 0.25 },
  { name: "Swarm of Ravens", cr: 0.25 },
  { name: "Tarrasque", cr: 30 },
  { name: "Thug", cr: 0.5 },
  { name: "Tiger", cr: 1 },
  { name: "Treant", cr: 9 },
  { name: "Tribal Warrior", cr: 0.125 },
  { name: "Triceratops", cr: 5 },
  { name: "Troll", cr: 5 },
  { name: "Tyrannosaurus Rex", cr: 8 },
  { name: "Unicorn", cr: 5 },
  { name: "Vampire", cr: 13 },
  { name: "Vampire Spawn", cr: 5 },
  { name: "Veteran", cr: 3 },
  { name: "Violet Fungus", cr: 0.25 },
  { name: "Vrock", cr: 6 },
  { name: "Warhorse", cr: 0.5 },
  { name: "Warhorse Skeleton", cr: 0.5 },
  { name: "Water Elemental", cr: 5 },
  { name: "Weasel", cr: 0 },
  { name: "Werebear", cr: 5 },
  { name: "Wereboar", cr: 4 },
  { name: "Wererat", cr: 2 },
  { name: "Weretiger", cr: 4 },
  { name: "Werewolf", cr: 3 },
  { name: "White Dragon Wyrmling", cr: 2 },
  { name: "Wight", cr: 3 },
  { name: "Will-o'-Wisp", cr: 2 },
  { name: "Winged Kobold", cr: 0.25 },
  { name: "Wolf", cr: 0.25 },
  { name: "Worg", cr: 0.5 },
  { name: "Wraith", cr: 5 },
  { name: "Wyvern", cr: 6 },
  { name: "Xorn", cr: 5 },
  { name: "Young Black Dragon", cr: 7 },
  { name: "Young Blue Dragon", cr: 9 },
  { name: "Young Brass Dragon", cr: 6 },
  { name: "Young Bronze Dragon", cr: 8 },
  { name: "Young Copper Dragon", cr: 7 },
  { name: "Young Gold Dragon", cr: 10 },
  { name: "Young Green Dragon", cr: 8 },
  { name: "Young Red Dragon", cr: 10 },
  { name: "Young Red Shadow Dragon", cr: 13 },
  { name: "Young Silver Dragon", cr: 9 },
  { name: "Young White Dragon", cr: 6 },
  { name: "Zombie", cr: 0.25 },
]
